# Site settings
author: David Charles
title: Bitsmart
header-img: img/home-bg.png
email: ratlover03@gmail.com
copyright_name: David Charles
description: > # this means to ignore newlines until "baseurl:"
  A journal 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  DavidCharles99

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
